import { useTranslation } from 'react-i18next'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import type { VoucherType } from '@/features/marketing'

const AUTO_CODE_TYPES: VoucherType[] = ['live', 'follow_prize']
const CODE_PREFIX = 'OZB'

type Props = {
  voucherType: VoucherType
  name: string; onName: (v: string) => void; nameError: string
  codeInput: string; onCode: (v: string) => void
  claimStart: string; onClaimStart: (v: string) => void
  claimEnd: string; onClaimEnd: (v: string) => void
  displayEarly: boolean; onDisplayEarly: (v: boolean) => void
}

export function VoucherBasicSection({
  voucherType, name, onName, nameError, codeInput, onCode,
  claimStart, onClaimStart, claimEnd, onClaimEnd, displayEarly, onDisplayEarly,
}: Props) {
  const { t } = useTranslation()
  const isFollowPrize = voucherType === 'follow_prize'
  const isAutoCode = AUTO_CODE_TYPES.includes(voucherType)
  const maxNameLen = isFollowPrize ? 20 : 100

  const targetLabel =
    voucherType === 'new_buyer' ? 'New Buyers'
    : voucherType === 'follow_prize' ? 'Followers'
    : 'Repeat Buyers'
  const showTargetBuyer = ['new_buyer', 'repeat_buyer', 'follow_prize'].includes(voucherType)

  return (
    <Card className="p-6">
      <h2 className="mb-5 text-base font-semibold text-text">
        {t('marketing.vouchers.create_form.basicInfo')}
      </h2>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="md:col-span-2">
          <Input
            label={t('marketing.vouchers.create_form.voucherName')}
            value={name}
            onChange={(e) => onName(e.target.value.slice(0, maxNameLen))}
            placeholder={isFollowPrize ? t('marketing.vouchers.create_form.nameFollowHint') : t('marketing.vouchers.create_form.nameHint')}
            error={nameError}
            trailing={<span className="text-xs text-muted">{name.length}/{maxNameLen}</span>}
            required
          />
          <p className="mt-1 text-xs text-muted">
            {isFollowPrize ? t('marketing.vouchers.create_form.nameFollowHint') : t('marketing.vouchers.create_form.nameHint')}
          </p>
        </div>

        <div>
          <label className="mb-1.5 block text-sm font-semibold text-text-secondary">
            {t('marketing.vouchers.create_form.voucherCode')}
          </label>
          {isAutoCode ? (
            <div className="flex h-11 items-center rounded-lg border border-border bg-bg px-3 text-sm text-muted">
              {t('marketing.vouchers.create_form.codeAutoGenerated')}
            </div>
          ) : (
            <div className="flex">
              <span className="flex items-center rounded-l-lg border border-r-0 border-border-strong bg-bg px-3 text-sm font-semibold text-text-secondary">
                {CODE_PREFIX}
              </span>
              <Input
                value={codeInput}
                onChange={(e) => onCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5))}
                placeholder="INPUT"
                className="rounded-l-none"
                trailing={<span className="text-xs text-muted">{codeInput.length}/5</span>}
              />
            </div>
          )}
          {!isAutoCode && (
            <p className="mt-1 text-xs text-muted">{t('marketing.vouchers.create_form.codeHint')}</p>
          )}
        </div>

        {showTargetBuyer && (
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-text-secondary">
              {t('marketing.vouchers.create_form.targetBuyer')}
            </label>
            <div className="flex h-11 items-center rounded-lg border border-border bg-bg px-3">
              <p className="text-sm font-semibold text-text">{targetLabel}</p>
            </div>
            {voucherType === 'new_buyer' && (
              <p className="mt-1 text-xs text-muted">{t('marketing.vouchers.create_form.newBuyerDesc')}</p>
            )}
            {isFollowPrize && (
              <p className="mt-1 text-xs text-muted">{t('marketing.vouchers.create_form.expiry')}</p>
            )}
          </div>
        )}
      </div>

      <div className="mt-4">
        <label className="mb-1.5 block text-sm font-semibold text-text-secondary">
          {isFollowPrize ? t('marketing.vouchers.create_form.claimPeriod') : t('marketing.vouchers.create_form.usagePeriod')}
        </label>
        <div className="flex items-center gap-2">
          <Input type="datetime-local" value={claimStart} onChange={(e) => onClaimStart(e.target.value)} className="flex-1" />
          <span className="shrink-0 text-muted">—</span>
          <Input type="datetime-local" value={claimEnd} onChange={(e) => onClaimEnd(e.target.value)} className="flex-1" />
        </div>
        {!isFollowPrize && (
          <label className="mt-2 flex cursor-pointer items-center gap-2 text-sm text-text-secondary">
            <input type="checkbox" checked={displayEarly} onChange={(e) => onDisplayEarly(e.target.checked)} className="rounded border-border-strong accent-brand" />
            {t('marketing.vouchers.create_form.displayEarly')}
          </label>
        )}
      </div>
    </Card>
  )
}
